# demo

name: demo

on:
    push:
        branches:
            - course-stage3-week2-01-github-actions
        paths:
            - '.github/workflows/**'
            - '__test__/**'
            - 'src/**'

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2 # git pull ，第三方的 cations
            - name: Use Node.js
              uses: actions/setup-node@v1 # 安装 nodejs ， 第三方的 cations
              with:
                  node-version: 14
            - name: print node version
              run: |
                  node -v
                  npm -v
                  echo 'hello github actions'
    test2:
        runs-on: ubuntu-latest
        steps:
            - run: touch a.txt
            - run: echo 100 > a.txt
            - run: cat a.txt
